#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
  path: /
  controller: App\Controller\ProductController::listAllProduct

listAllAdmin:
  path: /listAll
  controller: App\Controller\ProductController::listAll

delete:
  path: /delete/{id}
  controller: App\Controller\ProductController::doDeleteProduct

doUpdate:
  path: /doUpdate/{id}
  controller: App\Controller\ProductController::doUpdateProduct

update:
  path: /update/{id}
  controller: App\Controller\ProductController::updateProduct

doCreate:
  path: /doCreate
  controller: App\Controller\ProductController::doCreateProduct

create:
  path: /create
  controller: App\Controller\ProductController::createProduct
############
##Security##
############
appLogin:
  path: /login
  controller: App\Controller\SecurityController::login
  methods: GET|POST

app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

signUp:
  path: /signIn
  controller: App\Controller\SecurityController::signUp

doSignUp:
  path: /doSignIn
  controller: App\Controller\SecurityController::doSignUp

listUser:
  path: /listUser
  controller: App\Controller\SecurityController::listUser
#resetPass:
#  path: /resetPass
#  controller: App\Controller\SecurityController::resetPass
#doResetPass:
#  path: /doResetPass
#  controller: App\Controller\SecurityController::doResetPass
#changePass:
#  path: /changePass/{email}
#  controller: App\Controller\SecurityController::changePass
#doChangePass:
#  path: /doChangePass
#  controller: App\Controller\SecurityController::doChangePass