#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
  path: /
  controller: App\Controller\ProductController::index

listAll:
  path: /listAll
  controller: App\Controller\ProductController::listAllProduct

delete:
  path: /delete/{id}
  controller: App\Controller\ProductController::deleteProduct

updateForm:
  path: /updateForm/{id}
  controller: App\Controller\ProductController::updateProductForm

update:
  path: /update/{id}
  controller: App\Controller\ProductController::updateProduct

createForm:
  path: /form
  controller: App\Controller\ProductController::CreateProductForm

create:
  path: /product
  controller: App\Controller\ProductController::createProduct
############
##Security##
############
appLogin:
  path: /login
  controller: App\Controller\SecurityController::login
  methods: GET|POST

app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

resetPass:
  path: /resetPass
  controller: App\Controller\SecurityController::resetPass

doResetPass:
  path: /doResetPass
  controller: App\Controller\SecurityController::doResetPass

changePass:
  path: /changePass/{email}
  controller: App\Controller\SecurityController::changePass

doChangePass:
  path: /doChangePass
  controller: App\Controller\SecurityController::doChangePass

signIn:
  path: /signIn
  controller: App\Controller\SecurityController::signIn

doSignIn:
  path: /doSignIn
  controller: App\Controller\SecurityController::doSignIn